version: "2.8"

services:
      db_postgres:
            image: postgres
            environment:
                  POSTGRES_PASSWORD: 1
            restart: always
            network_mode: host

      db_redis:
            image: redis
            network_mode: host

      server:
            build:
                  context: .
                  dockerfile: Dockerfile
            image: server
            container_name: server
            depends_on:
                  - db_postgres
                  - db_redis
            network_mode: host

      front:
            build:
                  context: ../front/.
                  dockerfile: Dockerfile
            image: front
            container_name: front
            depends_on:
                  - server
            network_mode: host
