export { default as Register } from "./Register";
export { default as NotFound } from "./NotFound";
export { default as Index } from "./Index";
export { default as Login } from "./Login";
export { default as ChangePassword } from "./Change-password";
export { default as ForgotPassword } from "./Forgot-password";
export { default as Users } from "./Users";
export { default as EditProfile } from "./EditProfile";
export { default as SingleUser } from "./SingleUser";
